### ISSUE TITLE
STLs/ldo_deck_wire_cover_right.stl is identical to the original Voron Trident's part

### ISSUE THREAD

**Issue by maxim-kukushkin** [MotorDynamicsLab/LDOVoronTrident#4]
This file (referenced in the LDO's Assembly Guide) is actually identical to the original part of Voron Trident. I.e., the opening is the same size and doesn't fit the Toolhead cable. It's also clear when mounting it to the printer, as the cut in the panel is much wider than the whole in the printed part

**Comment by camerony** [comment]
added comment to printed part docs
